# 测试环境配置
server:
  port: 8080

spring:
  datasource:
    # 测试环境 Oracle（本地）
    url: jdbc:oracle:thin:@//192.168.104.167:1521/freepdb1

# 测试环境日志级别
logging:
  level:
    com.bcsport.admin: DEBUG
    com.bcsport.admin.mapper: DEBUG
    org.springframework: INFO
    org.apache.shiro: DEBUG

# 测试环境上传路径
bc.upload.path: D:/B.C.Sports/actions-runner/_work/BC_Sports/BC_Sports/project/src/main/resources/static/images
