-- 运动积分表新增自定义头像列（管理员代传，移动端徒步值排名展示）
-- 执行库：BC_SPORTS 主库（192.168.5.177:1521/orcl，bc_sports）
-- 回滚：ALTER TABLE BC_SPORTS_BCP_SPORT_POINTS DROP (AVATAR_URL);
ALTER TABLE BC_SPORTS_BCP_SPORT_POINTS ADD (AVATAR_URL VARCHAR2(500));

COMMENT ON COLUMN BC_SPORTS_BCP_SPORT_POINTS.AVATAR_URL IS '自定义头像URL(管理员代传,/images/avatar/xxx,空=移动端回退动物emoji)';

-- 验证：
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'BC_SPORTS_BCP_SPORT_POINTS' AND COLUMN_NAME = 'AVATAR_URL';
