-- ============================================================
-- BC好玩家 - 运动积分表 —— 主库 Oracle 执行
-- 全部幂等，可重复执行（DDL 用 user_tables/user_indexes 探测，建表列风格同 goods_data_schema.sql）
-- 导入走 R01 统一骨架（ExcelImportRunner），日志落 BC_SPORTS_SYS_IMPORT_LOG，本脚本只建业务表
-- ============================================================

-- 1. 建表：sporter + points 两个业务列 + 4 个系统审计列 + 逻辑删除位
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'BC_SPORTS_BCP_SPORT_POINTS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE BC_SPORTS_BCP_SPORT_POINTS (
        id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sporter      VARCHAR2(100 CHAR) NOT NULL,
        points       NUMBER NOT NULL,
        create_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
        update_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
        create_by    VARCHAR2(50 CHAR),
        update_by    VARCHAR2(50 CHAR),
        deleted      NUMBER(1) DEFAULT 0
      )';
    DBMS_OUTPUT.PUT_LINE('[1] BC_SPORTS_BCP_SPORT_POINTS 已创建');
  ELSE
    DBMS_OUTPUT.PUT_LINE('[1] BC_SPORTS_BCP_SPORT_POINTS 已存在，跳过建表');
  END IF;
END;
/

-- 2. 唯一索引：未删除记录内 sporter 唯一（一名运动员只保留一行积分，重复导入 MERGE 覆盖）
--    Oracle 无部分索引语法，用函数式唯一索引（同 uk_bcs_import_log_legacy 的写法）
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'UK_BCP_SPORT_POINTS_SPORTER';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_bcp_sport_points_sporter '
                   || 'ON BC_SPORTS_BCP_SPORT_POINTS (CASE WHEN deleted = 0 THEN sporter END)';
    DBMS_OUTPUT.PUT_LINE('[2] uk_bcp_sport_points_sporter 已创建');
  ELSE
    DBMS_OUTPUT.PUT_LINE('[2] uk_bcp_sport_points_sporter 已存在，跳过');
  END IF;
END;
/

-- 3. 排名索引：deleted + points DESC + sporter
--    支撑移动端榜单"取前N即停"(ROW_NUMBER ORDER BY points DESC, sporter)：十万级行数时
--    优化器可沿索引序直接取前100/前3行，避免每次请求全表排序。
--    姓名关键字搜索(WITH %kw% 前置通配)不走此索引仍为全表扫，十万级为几十毫秒，可接受
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_BCP_SPORT_POINTS_RANK';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_bcp_sport_points_rank '
                   || 'ON BC_SPORTS_BCP_SPORT_POINTS (deleted, points DESC, sporter)';
    DBMS_OUTPUT.PUT_LINE('[3] idx_bcp_sport_points_rank 已创建');
  ELSE
    DBMS_OUTPUT.PUT_LINE('[3] idx_bcp_sport_points_rank 已存在，跳过');
  END IF;
END;
/

COMMENT ON TABLE  BC_SPORTS_BCP_SPORT_POINTS IS 'BC好玩家运动积分（Excel 导入，走统一导入骨架）';
COMMENT ON COLUMN BC_SPORTS_BCP_SPORT_POINTS.sporter IS '运动员/玩家名，导入去重键';
COMMENT ON COLUMN BC_SPORTS_BCP_SPORT_POINTS.points IS '积分，整数';
COMMENT ON COLUMN BC_SPORTS_BCP_SPORT_POINTS.deleted IS '逻辑删除：0 正常 1 已删除';
