-- ============================================================
-- R01 统一导入日志表 BC_SPORTS_SYS_IMPORT_LOG —— 主库(BC_SPORTS, Oracle)执行
-- 设计文档：docs/R01导入骨架统一方案.md §4.2 / §4.3
--
-- 内容（全部幂等，可重复执行）：
--   1. 建表（IDENTITY 主键，列风格同 goods_data_schema.sql）
--   2. 普通索引 (import_type, create_time) 供各模块日志页分页
--   3. 函数式唯一索引 (CASE WHEN legacy_id IS NULL THEN NULL ELSE import_type END, legacy_id)
--      —— 历史搬迁幂等键。不能用普通复合唯一索引：Oracle 视 (type,NULL) 与 (type,NULL) 为重复，
--         切换后同模块第二条新日志（legacy_id 为 NULL）就会撞约束；函数式写法让新记录两键全 NULL 不进索引。
--   4. IDENTITY + 唯一索引首插验证（插两条同 type 且 legacy_id 为 NULL 的行再删除；失败则整段报错）
--   5. 搬迁按钮权限 system:import-log:migrate 挂「操作日志」(SYS_LOG) 下，授超管角色(role_id='1')
--
-- 旧 7 张 *_IMPORT_LOG 表：切换后停写停读，一个版本周期后另行 DROP（drop_legacy_import_logs.sql）。
-- 执行方式：SQL*Plus / SQL Developer 整段执行（含 PL/SQL 块与 "/"）；DBeaver 请用"执行脚本"模式并忽略 SET 行。
-- 字符列统一 CHAR 语义：中文文件名/用户名按字符计长，避免默认 BYTE 语义下 3 字节/汉字撞列宽导致整行日志丢失。
-- ============================================================
SET SERVEROUTPUT ON;

-- 1. 建表
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'BC_SPORTS_SYS_IMPORT_LOG';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE BC_SPORTS_SYS_IMPORT_LOG (
        id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        import_type    VARCHAR2(40 CHAR) NOT NULL,
        file_name      VARCHAR2(500 CHAR),
        file_size      NUMBER,
        total_count    NUMBER DEFAULT 0,
        success_count  NUMBER DEFAULT 0,
        fail_count     NUMBER DEFAULT 0,
        status         VARCHAR2(20 CHAR),
        error_msg      CLOB,
        create_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
        create_by      VARCHAR2(50 CHAR),
        legacy_id      NUMBER
      )';
    DBMS_OUTPUT.PUT_LINE('[1] BC_SPORTS_SYS_IMPORT_LOG 已创建');
  ELSE
    DBMS_OUTPUT.PUT_LINE('[1] BC_SPORTS_SYS_IMPORT_LOG 已存在，跳过建表');
  END IF;
END;
/

-- 2/3. 索引
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_BCS_IMPORT_LOG_TYPE_TIME';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_bcs_import_log_type_time ON BC_SPORTS_SYS_IMPORT_LOG (import_type, create_time)';
    DBMS_OUTPUT.PUT_LINE('[2] idx_bcs_import_log_type_time 已创建');
  ELSE
    DBMS_OUTPUT.PUT_LINE('[2] idx_bcs_import_log_type_time 已存在，跳过');
  END IF;

  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'UK_BCS_IMPORT_LOG_LEGACY';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_bcs_import_log_legacy ON BC_SPORTS_SYS_IMPORT_LOG '
                   || '(CASE WHEN legacy_id IS NULL THEN NULL ELSE import_type END, legacy_id)';
    DBMS_OUTPUT.PUT_LINE('[3] uk_bcs_import_log_legacy（函数式唯一索引）已创建');
  ELSE
    DBMS_OUTPUT.PUT_LINE('[3] uk_bcs_import_log_legacy 已存在，跳过');
  END IF;
END;
/

COMMENT ON TABLE  BC_SPORTS_SYS_IMPORT_LOG IS 'R01 全系统统一导入日志；旧各模块 *_IMPORT_LOG 表搬迁后只读，一个版本周期后 DROP';
COMMENT ON COLUMN BC_SPORTS_SYS_IMPORT_LOG.import_type IS '模块标识，对应 Java 枚举 ImportType';
COMMENT ON COLUMN BC_SPORTS_SYS_IMPORT_LOG.status      IS 'SUCCESS / PARTIAL / FAILED';
COMMENT ON COLUMN BC_SPORTS_SYS_IMPORT_LOG.legacy_id   IS '历史搬迁来源行 ID，新写入为 NULL';

-- 4. IDENTITY + 函数式唯一索引验证：同 type、legacy_id 均为 NULL 的两行必须都能插入
DECLARE
  v_id1 NUMBER;
  v_id2 NUMBER;
BEGIN
  INSERT INTO BC_SPORTS_SYS_IMPORT_LOG (import_type, file_name, status, create_by)
    VALUES ('__DDL_CHECK__', 'identity-verify-1', 'FAILED', 'ddl') RETURNING id INTO v_id1;
  INSERT INTO BC_SPORTS_SYS_IMPORT_LOG (import_type, file_name, status, create_by)
    VALUES ('__DDL_CHECK__', 'identity-verify-2', 'FAILED', 'ddl') RETURNING id INTO v_id2;
  DELETE FROM BC_SPORTS_SYS_IMPORT_LOG WHERE import_type = '__DDL_CHECK__';
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('[4] 验证通过：IDENTITY 生成 id=' || v_id1 || ',' || v_id2 || '；同 type 双 NULL legacy_id 未撞唯一索引');
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE_APPLICATION_ERROR(-20001, '[4] 验证失败（IDENTITY 或函数式唯一索引异常，请勿上线）: ' || SQLERRM);
END;
/

-- 5. 搬迁按钮权限（menu_type=2 按钮，不在侧边栏显示 visible=0），挂「操作日志」SYS_LOG 下
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'SYS_IMPORT_LOG_MIGRATE', 'SYS_LOG', '导入日志历史搬迁', NULL, 2,
       NULL, 'system:import-log:migrate', 3, 1, 0,
       'R01 一次性运维动作：把各模块旧导入日志表搬入统一表（幂等可重复执行），清理阶段删除', NULL,
       SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'SYS_IMPORT_LOG_MIGRATE');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'SYS_IMPORT_LOG_MIGRATE', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU
                    WHERE ROLE_ID = '1' AND MENU_ID = 'SYS_IMPORT_LOG_MIGRATE');

COMMIT;
