-- ==========================================================
-- 销售主明细 ODS 合并表
-- 数据来源: ODS_RETAIL_DETAIL(POS零售单) + ODS_SALE_DETAIL(销售/退货单)
-- 第9列明细ID统一为 ITEM_ID (源: RETAILITEM_ID / SALEITEM_ID)
-- 列类型 100% 继承自 ODS_RETAIL_DETAIL (已验证与 ODS_SALE_DETAIL 完全一致)
-- 目标: BI_DW.ODS_SALES_MAIN
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BI_DW.ODS_SALES_MAIN PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE BI_DW.ODS_SALES_MAIN AS
SELECT
    BILL_ID,
    BILL_NO,
    BILL_DATE,
    BILL_TIME,
    VIP_CODE,
    VIP_MOBILE,
    OMS_SOURCECODE,
    SALES_TYPE,
    RETAILITEM_ID AS ITEM_ID,
    BILL_POS_ID,
    BILL_POS_CODE,
    BILL_POS_NAME,
    STORE_ID,
    STORE_CODE,
    STORE_NAME,
    PRODUCT_CODE,
    PRODUCT_STYLE_NO,
    PRODUCT_NAME,
    COLORSALIAS,
    BARCODE,
    SIZES,
    QTY,
    RETAIL_PRICE,
    RETAIL_AMOUNT,
    TRANSACTION_AMOUNT,
    TOT_AMT_ACTUAL,
    AMT_RECEIVABLE,
    REVENUE,
    RECALC_REVENUE,
    ANCHOR_SUMMARYID,
    ANCHOR_SUMMARYNAME
FROM BI_DW.ODS_RETAIL_DETAIL
WHERE 1 = 0;

COMMENT ON TABLE  BI_DW.ODS_SALES_MAIN IS '销售主明细ODS合并(ODS_RETAIL_DETAIL零售单 + ODS_SALE_DETAIL销售/退货单)';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_ID            IS '单据ID';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_NO            IS '单据号';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_DATE          IS '单据日期';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_TIME          IS '提交时间';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.VIP_CODE           IS 'CRM会员卡号';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.VIP_MOBILE         IS 'CRM会员手机号';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.OMS_SOURCECODE     IS '网单来源单号';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.SALES_TYPE         IS '销售类型';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.ITEM_ID            IS '单据明细ID(零售明细ID/销售明细ID)';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_POS_ID        IS '营业员ID';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_POS_CODE      IS '营业员CODE';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BILL_POS_NAME      IS '营业员NAME';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.STORE_ID           IS '店铺ID';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.STORE_CODE         IS '店铺CODE';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.STORE_NAME         IS '店铺NAME';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.PRODUCT_CODE       IS '货品货号';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.PRODUCT_STYLE_NO   IS '货品款号';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.PRODUCT_NAME       IS '货品名称';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.COLORSALIAS        IS '货品颜色';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.BARCODE            IS '货品条码';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.SIZES              IS '货品尺码';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.QTY                IS '数量';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.RETAIL_PRICE       IS '零售价';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.RETAIL_AMOUNT      IS '零售金额';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.TRANSACTION_AMOUNT IS '实收金额(页面展示名,2026-09-16由成交金额改名)';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.TOT_AMT_ACTUAL     IS '成交金额(2026-09-14新增,源M_RETAILITEM同名列)';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.AMT_RECEIVABLE     IS '应收金额(2026-09-14新增,源M_RETAILITEM同名列)';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.REVENUE            IS '业绩金额';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.RECALC_REVENUE     IS '重算业绩';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.ANCHOR_SUMMARYID   IS '主播ID';
COMMENT ON COLUMN BI_DW.ODS_SALES_MAIN.ANCHOR_SUMMARYNAME IS '主播名称';

EXIT;
