-- =====================================================================
-- 销售预算(每日)填报  ODS_SALES_BUDGET_FILL_DAILY
-- SQL Server -> Oracle 转换
-- 默认 schema: BI_DW (ODS 数仓贴源层)
-- 类型映射: nvarchar(N)->VARCHAR2(N CHAR), datetime->DATE, decimal->NUMBER
-- 用 SYS 或有 BI_DW 建表权限的用户执行
-- =====================================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- 可重复执行: 先删后建
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BI_DW.ODS_SALES_BUDGET_FILL_DAILY PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE BI_DW.ODS_SALES_BUDGET_FILL_DAILY
(
    REGION_LEVEL1     VARCHAR2(100 CHAR) NOT NULL,
    REGION_LEVEL2     VARCHAR2(100 CHAR) NOT NULL,
    CHANNEL_PROPERTY  VARCHAR2(100 CHAR) NOT NULL,
    CHANNEL_DEF       VARCHAR2(100 CHAR) NOT NULL,
    STORE_NAME        VARCHAR2(100 CHAR) NOT NULL,
    BRAND_NAME        VARCHAR2(100 CHAR) NOT NULL,
    MONTHLY_NAME      VARCHAR2(20 CHAR)  NOT NULL,
    BUDGET_DTM        DATE               NOT NULL,
    BUDGET_AMOUNT     NUMBER(18,6)       NOT NULL,
    BUSINESS_TYPE     VARCHAR2(100 CHAR),
    BUSINESS_PROPERTY VARCHAR2(100 CHAR),
    SALES_TYPE        VARCHAR2(100 CHAR)
);

-- 唯一索引（店铺+品牌+预算日期，MERGE 判重依据，提升 upsert 性能）
CREATE UNIQUE INDEX UK_BUDGET_STORE_BRAND_DATE
    ON BI_DW.ODS_SALES_BUDGET_FILL_DAILY (STORE_NAME, BRAND_NAME, BUDGET_DTM);

-- 表注释
COMMENT ON TABLE  BI_DW.ODS_SALES_BUDGET_FILL_DAILY IS '销售预算(每日)填报';

-- 列注释
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.REGION_LEVEL1     IS '一级地区';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.REGION_LEVEL2     IS '二级地区';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.CHANNEL_PROPERTY  IS '渠道类型';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.CHANNEL_DEF       IS '渠道定义';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.STORE_NAME        IS '店铺名称';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.BRAND_NAME        IS '品牌名称';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.MONTHLY_NAME      IS '月份';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.BUDGET_DTM        IS '预算时间，YYYY-MM-DD';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.BUDGET_AMOUNT     IS '预算金额';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.BUSINESS_TYPE     IS '渠道性质';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.BUSINESS_PROPERTY IS '经营类型';
COMMENT ON COLUMN BI_DW.ODS_SALES_BUDGET_FILL_DAILY.SALES_TYPE        IS '销售类型';

EXIT;
