-- ==========================================================
-- 货品资料 - 建表脚本
-- 库: 主库 Oracle (BC_ERP_MANAGE)
-- ==========================================================

-- 1. 货品资料表
CREATE TABLE BC_SPORTS_BI_GOODS_OLDNEW (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand         VARCHAR2(100) NOT NULL,
    article_no    VARCHAR2(100) NOT NULL,
    season        VARCHAR2(100) NOT NULL,
    category      VARCHAR2(200),
    create_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
    update_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
    create_by     VARCHAR2(50),
    update_by     VARCHAR2(50),
    deleted       NUMBER(1) DEFAULT 0
);

-- 唯一索引（品牌+货号+产品季，忽略已删除记录）
CREATE UNIQUE INDEX UK_GOODS_OLDNEW_UNIQ ON BC_SPORTS_BI_GOODS_OLDNEW(brand, article_no, season) WHERE deleted = 0;

-- 2. 导入日志表
CREATE TABLE BC_SPORTS_GOODS_IMPORT_LOG (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name      VARCHAR2(200),
    file_size      NUMBER,
    total_count    NUMBER DEFAULT 0,
    success_count  NUMBER DEFAULT 0,
    fail_count     NUMBER DEFAULT 0,
    status         VARCHAR2(20),
    error_msg      CLOB,
    create_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
    create_by      VARCHAR2(50)
);

COMMIT;
