-- 隐藏 IHR 入职管理、调岗管理、离职管理菜单
-- 人员管理界面已包含这些功能，无需单独的菜单入口

-- 入职管理（含子按钮：同步）
UPDATE BC_SPORTS_SYS_MENU SET VISIBLE = 0, UPDATE_TIME = SYSTIMESTAMP, UPDATE_BY = 'admin'
WHERE ID IN ('IHR_ONBOARDING', 'IHR_ONBOARDING_SYNC');

-- 调岗管理
UPDATE BC_SPORTS_SYS_MENU SET VISIBLE = 0, UPDATE_TIME = SYSTIMESTAMP, UPDATE_BY = 'admin'
WHERE ID = 'IHR_UPDATE';

-- 离职管理（含子按钮：同步）
UPDATE BC_SPORTS_SYS_MENU SET VISIBLE = 0, UPDATE_TIME = SYSTIMESTAMP, UPDATE_BY = 'admin'
WHERE ID IN ('IHR_LEAVING', 'IHR_LEAVING_SYNC');

COMMIT;
