-- 操作日志菜单（放在系统管理目录 SYS_DIR 下，sort=6）
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('SYS_LOG', 'SYS_DIR', '操作日志', 'bi-clock-history', 1, '/system/log', 'system:log:query', 6, 1, 1, '系统操作日志', '', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 查询按钮
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('SYS_LOG_QUERY', 'SYS_LOG', '日志查询', '', 2, '', 'system:log:query', 1, 1, 0, '', '', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 清理按钮
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('SYS_LOG_REMOVE', 'SYS_LOG', '日志清理', '', 2, '', 'system:log:remove', 2, 1, 0, '', '', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 给管理员角色(role_id=1)分配菜单权限
INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
VALUES (SYS_GUID(), '1', 'SYS_LOG', SYSTIMESTAMP, 'admin');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
VALUES (SYS_GUID(), '1', 'SYS_LOG_QUERY', SYSTIMESTAMP, 'admin');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
VALUES (SYS_GUID(), '1', 'SYS_LOG_REMOVE', SYSTIMESTAMP, 'admin');

COMMIT;
