-- 在线用户菜单（放在系统管理目录 SYS_MENU 下）
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('SYS_ONLINE_USER', 'SYS_MENU', '在线用户', 'bi-people', 1, '/system/online-user', 'system:online:list', 100, 1, 1, '', 'cyan', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 查询按钮
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('SYS_ONLINE_USER_QUERY', 'SYS_ONLINE_USER', '查询', '', 2, '', 'system:online:list', 1, 1, 1, '', '', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 强制下线按钮
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('SYS_ONLINE_USER_KICK', 'SYS_ONLINE_USER', '强制下线', '', 2, '', 'system:online:kick', 2, 1, 1, '', '', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);