-- ==========================================================
-- 店铺日预算 - 建表 + 菜单脚本
-- 导入日志表: BC_SPORTS.BC_SPORTS_BUDGET_LOG (走主库 bc_sports)
-- 业务表: BI_DW.ODS_SALES_BUDGET_FILL_DAILY (已在 create_ods_sales_budget_fill_daily.sql 创建)
-- 菜单: 挂在 BI管理(BI_DIR) 下
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- ==========================================================
-- 1. 导入日志表(BC_SPORTS schema, identity 自增ID, 结构照抄 BC_SPORTS_GOODS_IMPORT_LOG)
-- ==========================================================
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'BC_SPORTS_BUDGET_LOG';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BC_SPORTS_BUDGET_LOG (
          id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          file_name      VARCHAR2(200),
          file_size      NUMBER,
          total_count    NUMBER DEFAULT 0,
          success_count  NUMBER DEFAULT 0,
          fail_count     NUMBER DEFAULT 0,
          status         VARCHAR2(20),
          error_msg      CLOB,
          create_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
          create_by      VARCHAR2(50)
      )]';
    DBMS_OUTPUT.PUT_LINE('BC_SPORTS_BUDGET_LOG created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('BC_SPORTS_BUDGET_LOG already exists, skip');
  END IF;
END;
/

-- ==========================================================
-- 2. 菜单(挂在 BI_DIR 下) + 按钮权限 + 授权给超管 role_id='1'
-- 用 BC_SPORTS 身份执行(菜单表在 bc_sports schema)
-- ==========================================================

-- 2.1 页面菜单 (menu_type=1)
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_SHOP_DAILY_BUDGET', 'BI_DIR', '店铺日预算', 'bi-currency-bitcoin', 1,
       '/bi/shop-daily-budget', 'bi:shop-daily-budget:query', 40, 1, 1,
       '店铺每日预算查询与导入', NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_SHOP_DAILY_BUDGET');

-- 2.2 导入按钮权限 (menu_type=2, 不在侧边栏显示 visible=0)
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_SHOP_DAILY_BUDGET_IMPORT', 'BI_SHOP_DAILY_BUDGET', '导入', NULL, 2,
       NULL, 'bi:shop-daily-budget:import', 1, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_SHOP_DAILY_BUDGET_IMPORT');

-- 2.3 授权给超管角色 (role_id='1')
INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_SHOP_DAILY_BUDGET', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_SHOP_DAILY_BUDGET');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_SHOP_DAILY_BUDGET_IMPORT', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_SHOP_DAILY_BUDGET_IMPORT');

COMMIT;

EXIT;
