-- ==========================================================
-- 尺码组导入日志表 - 建表脚本
-- 库: 主库 Oracle (BC_SPORTS)
-- 与 BC_SPORTS_BUDGET_LOG / BC_SPORTS_GOODS_IMPORT_LOG 同构
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'STICKER_SIZE_GROUP_IMPORT_LOG';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE STICKER_SIZE_GROUP_IMPORT_LOG (
          id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          file_name      VARCHAR2(200),
          file_size      NUMBER,
          total_count    NUMBER DEFAULT 0,
          success_count  NUMBER DEFAULT 0,
          fail_count     NUMBER DEFAULT 0,
          status         VARCHAR2(20),
          error_msg      CLOB,
          create_time    TIMESTAMP DEFAULT SYSTIMESTAMP,
          create_by      VARCHAR2(50)
      )]';
    DBMS_OUTPUT.PUT_LINE('STICKER_SIZE_GROUP_IMPORT_LOG created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('STICKER_SIZE_GROUP_IMPORT_LOG already exists, skip');
  END IF;
END;
/
COMMIT;
EXIT;
