-- ==========================================================
-- 存储过程: BI_DW.SP_FILL_ODS_SALES_MAIN
-- 功能: 按 BILL_TIME(提交时间)范围增量刷新 ODS_SALES_MAIN
--   ① 幂等清理本范围旧数据(按 BILL_TIME)
--   ② 灌入 零售单(ODS_RETAIL_DETAIL) + 销售退货单(ODS_SALE_DETAIL)
--        两表金额列含 TOT_AMT_ACTUAL(实收) / AMT_RECEIVABLE(应收) 一并灌入
--   ③ 主播达人单店铺改写: ANCHOR_SUMMARYNAME 匹配主库达人店铺映射表
--        (BC_SPORTS.BC_SPORTS_BI_TALENT_STORE, 后台"达人店铺管理"手工维护)
--        命中 -> STORE_CODE/STORE_NAME 改为达人绑定店仓; 未命中不动
--        只改 code/name 两列, STORE_ID 保持原值; 退货单主播为NULL天然不受影响
--   ④ MERGE 更新小程序订单: OMS_SOURCECODE 关联 NX_TRADE_CUSTOMER_GUIDER_SHOP.OUT_TRADE_ID
--        匹配上 -> SALES_TYPE='小程序', VIP_MOBILE=BIND_MOBILE, 营业员(EMPLOYEE_NUM/NAME), 店铺(OUT_ID/SHOP_NAME)
--        店铺关联不上 -> STORE_CODE='BCHY', STORE_NAME='边城会员中心店'
--        未匹配小程序的订单保持原值不动
--        店铺白名单(BC_SPORTS.BC_SPORTS_BI_STORE_WHITELIST, 按订单当前 STORE_CODE 命中, 注意是"反向"白名单):
--        命中 -> STORE_CODE/STORE_NAME 保持原值不改写(③主播改写结果也保留), 只更新其余4列;
--        未命中 -> 原逻辑 6 列全改(含 BCHY 兜底)。白名单判断在③之后, 用④执行时的当前 STORE_CODE
-- 优先级: ③在④之前执行, 同一单若两规则都命中, 小程序(④)后执行覆盖主播(③) —— 小程序优先
-- 主播两列(ANCHOR_SUMMARYID/ANCHOR_SUMMARYNAME): ②-1 从 ODS_RETAIL_DETAIL 透传,
--        ②-2 退货单源表 ODS_SALE_DETAIL 无此两列, 灌 NULL
-- 关联键已验证: OUT_TRADE_ID / EMPLOYEE_ID / SHOP_ID 均唯一;
--        达人名称在映射表内唯一(uk_bi_talent_store_talent), ③ 的 MERGE 源不多条, 无 ORA-30926 风险
-- 注意: ② 用 EXECUTE IMMEDIATE 动态SQL, 绕过 PL/SQL 编译期 INSERT...SELECT 字符集推断(ORA-12704)
--       NVARCHAR2 字段用 TO_CHAR 转换(避免 MERGE 字符集 ORA-12704);
--       ③涉及的列(ANCHOR_SUMMARYNAME/STORE_CODE/STORE_NAME/TALENT_NAME)均为 VARCHAR2, 无需转换
-- 前置权限: bc_sports 需授权 GRANT SELECT ON BC_SPORTS_BI_TALENT_STORE TO BI_DW
--       (存储过程为定义者权限, 直接授权即生效; 已收入 talent_store_schema.sql 第4节)
--       bc_sports 需授权 GRANT SELECT ON BC_SPORTS_BI_STORE_WHITELIST TO BI_DW
--       (④白名单判断用; 已收入 store_whitelist_schema.sql 第4节)
-- 参数: P_START_TIME / P_END_TIME  (VARCHAR2, 格式 YYYY-MM-DD HH24:MI:SS, 如 '2026-07-28 00:00:00')
--       用 VARCHAR2 而非 DATE, 避免 Kettle 调用时 NLS_DATE_FORMAT 隐式转换报 ORA-01861
-- 调用: EXEC SP_FILL_ODS_SALES_MAIN('2026-07-28 00:00:00','2026-08-05 23:59:59');
-- 变更: 2026-09-14 新增③主播达人单店铺改写; 同步库里已存在的 TOT_AMT_ACTUAL/AMT_RECEIVABLE 两列入本副本
--       2026-09-24 ④新增店铺白名单: 命中 BC_SPORTS_BI_STORE_WHITELIST 的订单不改写店铺两列, 其余4列照常
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE OR REPLACE PROCEDURE BI_DW.SP_FILL_ODS_SALES_MAIN(
    P_START_TIME IN VARCHAR2,
    P_END_TIME   IN VARCHAR2)
AS
  -- 字符串参数 -> DATE(固定掩码, 不依赖会话 NLS_DATE_FORMAT)
  V_START DATE := TO_DATE(P_START_TIME, 'YYYY-MM-DD HH24:MI:SS');
  V_END   DATE := TO_DATE(P_END_TIME,   'YYYY-MM-DD HH24:MI:SS');
BEGIN
  -- ① 幂等清理本时间范围(按 BILL_TIME 提交时间)
  DELETE FROM BI_DW.ODS_SALES_MAIN
   WHERE BILL_TIME BETWEEN V_START AND V_END;

  -- ②-1 零售单 (明细ID RETAILITEM_ID -> ITEM_ID, 主播两列直接透传)  动态SQL
  EXECUTE IMMEDIATE
    'INSERT INTO BI_DW.ODS_SALES_MAIN (
        BILL_ID, BILL_NO, BILL_DATE, BILL_TIME, VIP_CODE, VIP_MOBILE,
        OMS_SOURCECODE, SALES_TYPE, ITEM_ID, BILL_POS_ID, BILL_POS_CODE,
        BILL_POS_NAME, STORE_ID, STORE_CODE, STORE_NAME, PRODUCT_CODE,
        PRODUCT_STYLE_NO, PRODUCT_NAME, COLORSALIAS, BARCODE, SIZES, QTY,
        RETAIL_PRICE, RETAIL_AMOUNT, TRANSACTION_AMOUNT, REVENUE,
         RECALC_REVENUE,
        ANCHOR_SUMMARYID, ANCHOR_SUMMARYNAME,TOT_AMT_ACTUAL,AMT_RECEIVABLE)
     SELECT BILL_ID, BILL_NO, BILL_DATE, BILL_TIME, VIP_CODE, VIP_MOBILE,
         OMS_SOURCECODE, SALES_TYPE, RETAILITEM_ID, BILL_POS_ID, BILL_POS_CODE,
         BILL_POS_NAME, STORE_ID, STORE_CODE, STORE_NAME, PRODUCT_CODE,
         PRODUCT_STYLE_NO, PRODUCT_NAME, COLORSALIAS, BARCODE, SIZES, QTY,
         RETAIL_PRICE, RETAIL_AMOUNT, TRANSACTION_AMOUNT, REVENUE,
          RECALC_REVENUE,
         ANCHOR_SUMMARYID, ANCHOR_SUMMARYNAME,TOT_AMT_ACTUAL,AMT_RECEIVABLE
       FROM BI_DW.ODS_RETAIL_DETAIL
      WHERE BILL_TIME BETWEEN :1 AND :2'
    USING V_START, V_END;

  -- ②-2 销售退货单 (明细ID SALEITEM_ID -> ITEM_ID, 源表无主播列, 灌NULL)  动态SQL
  EXECUTE IMMEDIATE
    'INSERT INTO BI_DW.ODS_SALES_MAIN (
        BILL_ID, BILL_NO, BILL_DATE, BILL_TIME, VIP_CODE, VIP_MOBILE,
        OMS_SOURCECODE, SALES_TYPE, ITEM_ID, BILL_POS_ID, BILL_POS_CODE,
        BILL_POS_NAME, STORE_ID, STORE_CODE, STORE_NAME, PRODUCT_CODE,
        PRODUCT_STYLE_NO, PRODUCT_NAME, COLORSALIAS, BARCODE, SIZES, QTY,
        RETAIL_PRICE, RETAIL_AMOUNT, TRANSACTION_AMOUNT, REVENUE,
         RECALC_REVENUE,
        ANCHOR_SUMMARYID, ANCHOR_SUMMARYNAME,TOT_AMT_ACTUAL,AMT_RECEIVABLE)
     SELECT BILL_ID, BILL_NO, BILL_DATE, BILL_TIME, VIP_CODE, VIP_MOBILE,
         OMS_SOURCECODE, SALES_TYPE, SALEITEM_ID, BILL_POS_ID, BILL_POS_CODE,
         BILL_POS_NAME, STORE_ID, STORE_CODE, STORE_NAME, PRODUCT_CODE,
         PRODUCT_STYLE_NO, PRODUCT_NAME, COLORSALIAS, BARCODE, SIZES, QTY,
         RETAIL_PRICE, RETAIL_AMOUNT, TRANSACTION_AMOUNT, REVENUE,
          RECALC_REVENUE,
         NULL, NULL,TOT_AMT_ACTUAL,AMT_RECEIVABLE
       FROM BI_DW.ODS_SALE_DETAIL
      WHERE BILL_TIME BETWEEN :1 AND :2'
    USING V_START, V_END;

  -- ③ 主播达人单店铺改写: 主播名(去首尾空格)匹配达人店铺映射表, 命中改写店仓编码/名称
  --    先于④执行, 同单重叠时小程序(④)覆盖本步结果; STORE_ID 不改
  MERGE INTO BI_DW.ODS_SALES_MAIN m
  USING (
        SELECT ts.TALENT_NAME, ts.STORE_CODE, ts.STORE_NAME
          FROM BC_SPORTS.BC_SPORTS_BI_TALENT_STORE ts
         WHERE ts.DELETED = 0
  ) ts
  ON ( TRIM(m.ANCHOR_SUMMARYNAME) = ts.TALENT_NAME
       AND m.BILL_TIME BETWEEN V_START AND V_END )
  WHEN MATCHED THEN UPDATE SET
         m.STORE_CODE = ts.STORE_CODE,
         m.STORE_NAME = ts.STORE_NAME;

  -- ④ MERGE 更新小程序订单(仅 OUT_TRADE_ID 能匹配上的)
  --    店铺白名单(反向): 当前 STORE_CODE 命中 BC_SPORTS_BI_STORE_WHITELIST 的订单
  --    不改写 STORE_CODE/STORE_NAME(保持③之后的现值), 其余4列照常; 未命中走原逻辑6列全改
  MERGE INTO BI_DW.ODS_SALES_MAIN m
  USING (
        SELECT t.OUT_TRADE_ID,
               TO_CHAR(t.BIND_MOBILE) AS NEW_MOBILE,
               TO_CHAR(e.EMPLOYEE_NUM) AS NEW_POS_CODE,
               TO_CHAR(e.NAME)         AS NEW_POS_NAME,
               CASE WHEN s.OUT_ID IS NULL THEN 'BCHY'
                    ELSE TO_CHAR(s.OUT_ID) END AS NEW_STORE_CODE,
               NVL(TO_CHAR(s.SHOP_NAME), '边城会员中心店') AS NEW_STORE_NAME
          FROM BI_DW.NX_TRADE_CUSTOMER_GUIDER_SHOP t
          LEFT JOIN BI_DW.NX_YUN_EMPLOYEE e
                 ON t.SG_EXCLUSIVE_GUIDE_ID = e.EMPLOYEE_ID
          LEFT JOIN BI_DW.NX_YUN_SHOP s
                 ON t.SG_EXCLUSIVE_SHOP_ID = s.SHOP_ID
  ) nx
  ON ( m.OMS_SOURCECODE = nx.OUT_TRADE_ID
       AND m.BILL_TIME BETWEEN V_START AND V_END )
  WHEN MATCHED THEN UPDATE SET
         m.SALES_TYPE    = '小程序',
         m.VIP_MOBILE    = nx.NEW_MOBILE,
         m.BILL_POS_CODE = nx.NEW_POS_CODE,
         m.BILL_POS_NAME = nx.NEW_POS_NAME,
         m.STORE_CODE    = CASE WHEN EXISTS (
                              SELECT 1 FROM BC_SPORTS.BC_SPORTS_BI_STORE_WHITELIST w
                               WHERE w.DELETED = 0
                                 AND w.STORE_CODE = m.STORE_CODE)
                            THEN m.STORE_CODE ELSE nx.NEW_STORE_CODE END,
         m.STORE_NAME    = CASE WHEN EXISTS (
                              SELECT 1 FROM BC_SPORTS.BC_SPORTS_BI_STORE_WHITELIST w
                               WHERE w.DELETED = 0
                                 AND w.STORE_CODE = m.STORE_CODE)
                            THEN m.STORE_NAME ELSE nx.NEW_STORE_NAME END;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END SP_FILL_ODS_SALES_MAIN;
/

SHOW ERRORS;
EXIT;
