-- ==========================================================
-- 存储过程: BI_DW.SP_UPDATE_NEW_OLD
-- 功能: 新旧货分类 (对应 SQL Server dw.SP_SALES_Update_New_Old)
--   ① 构建 物料×销售季节 笛卡尔积 -> DIM_PRODUCT_NEW_OLD
--   ② 分步 UPDATE new_old_type (下季新品/当季新品/专供新品/当季旧货/当季尾货/过季旧品/过季尾货/清货)
--   ③ BC_SPORTS_BI_GOODS_OLDNEW 兜底覆盖(货号+销售年季, 命中即覆盖; 原 CONFIG 表已废弃, 由该表替代维护)
--   ④ 按 BILL_TIME 范围 回填 ODS_SALES_MAIN.NEW_OLD_NAME_ADJUST
-- 数据源: ODS_M_PRODUCT(物料维度) + DIM_TIME_MAIN(时间维度)
-- 参数: P_START_TIME / P_END_TIME (VARCHAR2, YYYY-MM-DD HH24:MI:SS)
-- 注意: ①用 EXECUTE IMMEDIATE 避免PL/SQL编译期 INSERT...SELECT 字符集推断
--       TO_NUMBER(x DEFAULT NULL ON CONVERSION ERROR) 防非数字年份报错(SQL内置, 19c)
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE OR REPLACE PROCEDURE BI_DW.SP_UPDATE_NEW_OLD(
    P_START_TIME IN VARCHAR2,
    P_END_TIME   IN VARCHAR2)
AS
  V_START DATE := TO_DATE(P_START_TIME, 'YYYY-MM-DD HH24:MI:SS');
  V_END   DATE := TO_DATE(P_END_TIME,   'YYYY-MM-DD HH24:MI:SS');
BEGIN
  -- ① 清空 + 构建 物料×销售季节(笛卡尔积), new_old_type 初始 NULL
  EXECUTE IMMEDIATE 'TRUNCATE TABLE BI_DW.DIM_PRODUCT_NEW_OLD';

  EXECUTE IMMEDIATE
    'INSERT INTO BI_DW.DIM_PRODUCT_NEW_OLD (
        MATERIAL_ID, MATERIAL_CODE, MATERIAL_NAME, MAT_TYPE_NAME, CARD_NAME, ITEM_NAME,
        PRODUCT_YEAR_SEASON_NO, PRODUCT_YEAR, PRODUCT_SEASON, PRODUCT_YEAR_SEASON,
        SALE_YEAR_SEASON_NO, SALE_YEAR, SALE_SEASON, SALE_YEAR_SEASON,
        NEW_OLD_TYPE, DATA_CREATE_DTM)
     WITH bas_material AS (
        SELECT mp.ID AS material_id, mp.NAME AS material_code, mp.GOODSNAME AS material_name,
               mp.MAT_TYPE_NAME, mp.CARD_NAME, mp.ITEM_NAME,
               mp.YEAR_NO AS product_year,
               CASE WHEN mp.SEASON_NAME = ''春夏'' THEN ''SS'' ELSE ''AW'' END AS product_season,
               SUBSTR(mp.YEAR_NO, -2) || CASE WHEN mp.SEASON_NAME = ''春夏'' THEN ''SS'' ELSE ''AW'' END AS product_year_season,
               dtm.PRODUCT_YEAR_SEASON_NO
          FROM BI_DW.ODS_M_PRODUCT mp
          LEFT JOIN (SELECT DISTINCT PRODUCT_SEASON, PRODUCT_YEAR_SEASON_NO FROM BI_DW.DIM_TIME_MAIN) dtm
                 ON dtm.PRODUCT_SEASON = SUBSTR(mp.YEAR_NO, -2) || CASE WHEN mp.SEASON_NAME = ''春夏'' THEN ''SS'' ELSE ''AW'' END
     ),
     bas_dtm AS (
        SELECT DISTINCT PRODUCT_YEAR_SEASON_NO AS sale_year_season_no,
               ''20'' || SUBSTR(PRODUCT_SEASON, 1, 2) AS sale_year,
               SUBSTR(PRODUCT_SEASON, -2) AS sale_season,
               PRODUCT_SEASON AS sale_year_season
          FROM BI_DW.DIM_TIME_MAIN
         WHERE TO_NUMBER(DATE_YEAR DEFAULT NULL ON CONVERSION ERROR) BETWEEN 2018 AND TO_NUMBER(TO_CHAR(SYSDATE,''YYYY'')) + 2
     )
     SELECT m.material_id, m.material_code, m.material_name, m.mat_type_name, m.card_name, m.item_name,
            m.PRODUCT_YEAR_SEASON_NO, m.product_year, m.product_season, m.product_year_season,
            d.sale_year_season_no, d.sale_year, d.sale_season, d.sale_year_season,
            CAST(NULL AS VARCHAR2(50)), SYSDATE
       FROM bas_material m, bas_dtm d';

  -- ② 分步分类 UPDATE (忠于原 SP 顺序, 后者覆盖前者)
  -- 下季新品(常规)
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '下季新品'
   WHERE CARD_NAME NOT IN ('LOWA', 'LEKI徒步')
     AND PRODUCT_YEAR_SEASON_NO IS NOT NULL AND SALE_YEAR_SEASON_NO IS NOT NULL
     AND ((PRODUCT_SEASON = SALE_SEASON AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO <= -2)
       OR (PRODUCT_SEASON <> SALE_SEASON AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO <= -1));
  -- 下季新品(LOWA/LEKI): 销售年 - 货品年 < 0
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '下季新品'
   WHERE CARD_NAME IN ('LOWA', 'LEKI徒步')
     AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
       - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) < 0;
  -- 当季新品
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '当季新品'
   WHERE (PRODUCT_YEAR_SEASON_NO = SALE_YEAR_SEASON_NO AND CARD_NAME NOT IN ('LOWA','LEKI徒步'))
      OR (CARD_NAME IN ('LOWA','LEKI徒步')
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) >= 0
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) < 2);
  -- 专供新品
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '专供新品'
   WHERE CARD_NAME NOT IN ('LOWA','LEKI徒步')
     AND PRODUCT_YEAR_SEASON_NO = SALE_YEAR_SEASON_NO
     AND ITEM_NAME = '电商专供';
  -- 当季旧货
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '当季旧货'
   WHERE (CARD_NAME NOT IN ('LOWA','LEKI徒步')
          AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO = 2)
      OR (CARD_NAME IN ('LOWA','LEKI徒步')
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) >= 2
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) < 4
          AND SALE_SEASON = PRODUCT_SEASON);
  -- 当季尾货
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '当季尾货'
   WHERE (CARD_NAME NOT IN ('LOWA','LEKI徒步')
          AND SALE_SEASON = PRODUCT_SEASON AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO > 2)
      OR (CARD_NAME IN ('LOWA','LEKI徒步') AND SALE_SEASON = PRODUCT_SEASON
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) >= 4);
  -- 过季旧品
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '过季旧品'
   WHERE (CARD_NAME NOT IN ('LOWA','LEKI徒步')
          AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO = 1)
      OR (CARD_NAME IN ('LOWA','LEKI徒步')
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) >= 2
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) < 4
          AND SALE_SEASON <> PRODUCT_SEASON);
  -- 过季尾货
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '过季尾货'
   WHERE (CARD_NAME NOT IN ('LOWA','LEKI徒步')
          AND SALE_SEASON <> PRODUCT_SEASON AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO > 1)
      OR (CARD_NAME IN ('LOWA','LEKI徒步') AND SALE_SEASON <> PRODUCT_SEASON
          AND TO_NUMBER(SALE_YEAR   DEFAULT NULL ON CONVERSION ERROR)
            - TO_NUMBER(PRODUCT_YEAR DEFAULT NULL ON CONVERSION ERROR) >= 4);
  -- 清货
  UPDATE BI_DW.DIM_PRODUCT_NEW_OLD SET NEW_OLD_TYPE = '清货'
   WHERE CARD_NAME IN ('NATURE URBAN','NORTHLAND',' NORTHLAND.KIDS','HALTI')
     AND SALE_YEAR_SEASON_NO IS NOT NULL AND PRODUCT_YEAR_SEASON_NO IS NOT NULL
     AND ((SALE_SEASON <> PRODUCT_SEASON AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO > 3)
       OR (SALE_SEASON = PRODUCT_SEASON AND SALE_YEAR_SEASON_NO - PRODUCT_YEAR_SEASON_NO > 4));

  -- ③b 兜底覆盖(最高优先级): BC_SPORTS.BC_SPORTS_BI_GOODS_OLDNEW
  --     按 货号+销售年季 匹配, 命中即覆盖(含已分类行)
  MERGE INTO BI_DW.DIM_PRODUCT_NEW_OLD dim
  USING (SELECT ARTICLE_NO, SEASON, CATEGORY
           FROM BC_SPORTS.BC_SPORTS_BI_GOODS_OLDNEW
          WHERE NVL(DELETED, 0) = 0
            AND CATEGORY IS NOT NULL) gon
     ON (dim.MATERIAL_CODE = gon.ARTICLE_NO AND dim.SALE_YEAR_SEASON = gon.SEASON)
   WHEN MATCHED THEN UPDATE SET dim.NEW_OLD_TYPE = gon.CATEGORY, dim.DATA_CREATE_DTM = SYSDATE;

  -- ④ 回填 ODS_SALES_MAIN.NEW_OLD_NAME_ADJUST (按 BILL_TIME 范围)
  MERGE INTO BI_DW.ODS_SALES_MAIN sm
  USING (
     SELECT sm2.ROWID AS rid, dim.NEW_OLD_TYPE
       FROM BI_DW.ODS_SALES_MAIN sm2
       JOIN BI_DW.ODS_M_PRODUCT mp ON mp.NAME = sm2.PRODUCT_CODE
       JOIN BI_DW.DIM_TIME_MAIN dt ON TRUNC(dt.DATE_INTACT) = TRUNC(sm2.BILL_TIME)
       JOIN BI_DW.DIM_PRODUCT_NEW_OLD dim
         ON dim.MATERIAL_ID = TO_CHAR(mp.ID)
        AND dim.SALE_YEAR_SEASON = dt.PRODUCT_SEASON
        AND dim.PRODUCT_YEAR_SEASON = (SUBSTR(mp.YEAR_NO,-2) || CASE WHEN mp.SEASON_NAME = '春夏' THEN 'SS' ELSE 'AW' END)
      WHERE sm2.BILL_TIME BETWEEN V_START AND V_END
  ) x ON (sm.ROWID = x.rid)
   WHEN MATCHED THEN UPDATE SET sm.NEW_OLD_NAME_ADJUST = x.NEW_OLD_TYPE;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END SP_UPDATE_NEW_OLD;
/

SHOW ERRORS;
EXIT;
