-- 贴纸打印 - 新增「贴纸资料维护」菜单
-- 1. 菜单
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('STICKER_DATA', 'STICKER_DIR', '贴纸资料维护', 'bi-file-earmark-text', 1, '/sticker/data', 'sticker:data:query', 2, 1, 1, '贴纸打印货品资料维护', null, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 2. 按钮权限
INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('STICKER_DATA_ADD', 'STICKER_DATA', '新增', null, 2, null, 'sticker:data:add', 1, 1, 0, null, null, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('STICKER_DATA_EDIT', 'STICKER_DATA', '编辑', null, 2, null, 'sticker:data:edit', 2, 1, 0, null, null, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

INSERT INTO BC_SPORTS_SYS_MENU (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE, DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
VALUES ('STICKER_DATA_DEL', 'STICKER_DATA', '删除', null, 2, null, 'sticker:data:delete', 3, 1, 0, null, null, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0);

-- 3. 绑定到 admin 角色 (role_id=1)
INSERT INTO bc_sports_sys_role_menu (id, role_id, menu_id, create_time, create_by)
SELECT rawtohex(sys_guid()), '1', id, SYSTIMESTAMP, 'admin' FROM bc_sports_sys_menu
WHERE id IN ('STICKER_DATA', 'STICKER_DATA_ADD', 'STICKER_DATA_EDIT', 'STICKER_DATA_DEL');

COMMIT;
