-- ============================================================
-- 贴纸资料导入日志表
-- 目标数据库: Oracle > BC_ERP_MANAGE（本地主库）
-- 说明: 记录每次批量导入贴纸资料的结果（数据本身写伯俊 ERP M_PRODUCT）
-- 幂等: 已存在则跳过
--
-- ⚠ 迁移注意（历史事故见 fix_identity_columns_ora00001.sql）:
--    本表 id 用 IDENTITY 自增，应用侧 INSERT 不带 id。若日后跨库迁移采用
--    "重建表 + 显式 id 灌数"方式，identity 内部序列不会推进，应用插入会撞
--    ORA-00001。届时执行一次:
--      ALTER TABLE STICKER_DATA_IMPORT_LOG MODIFY (id GENERATED BY DEFAULT AS IDENTITY START WITH LIMIT VALUE);
-- ============================================================

-- 导入日志表
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'STICKER_DATA_IMPORT_LOG';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE STICKER_DATA_IMPORT_LOG (
        id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_name     VARCHAR2(200),
        file_size     NUMBER,
        total_count   NUMBER DEFAULT 0,
        success_count NUMBER DEFAULT 0,
        fail_count    NUMBER DEFAULT 0,
        status        VARCHAR2(20),
        error_msg     CLOB,
        create_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
        create_by     VARCHAR2(50)
    )';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE STICKER_DATA_IMPORT_LOG IS ''贴纸资料导入日志''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN STICKER_DATA_IMPORT_LOG.file_name IS ''导入文件名''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN STICKER_DATA_IMPORT_LOG.total_count IS ''总行数''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN STICKER_DATA_IMPORT_LOG.success_count IS ''成功行数''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN STICKER_DATA_IMPORT_LOG.fail_count IS ''失败行数''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN STICKER_DATA_IMPORT_LOG.status IS ''状态: SUCCESS/PARTIAL/FAILED''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN STICKER_DATA_IMPORT_LOG.error_msg IS ''错误明细''';
    DBMS_OUTPUT.PUT_LINE('Table STICKER_DATA_IMPORT_LOG created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Table STICKER_DATA_IMPORT_LOG already exists');
  END IF;
END;
/

-- 按时间倒序索引（导入记录默认按时间倒序查）
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_indexes WHERE index_name = 'IDX_STICKER_DATA_LOG_TIME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_STICKER_DATA_LOG_TIME ON STICKER_DATA_IMPORT_LOG (create_time DESC)';
    DBMS_OUTPUT.PUT_LINE('Index IDX_STICKER_DATA_LOG_TIME created');
  END IF;
END;
/
