-- ==========================================================
-- 店铺白名单(小程序步骤不改写店铺) - 建表脚本 —— 主库 Oracle 执行(BC_SPORTS)
-- 业务表: BC_SPORTS_BI_STORE_WHITELIST（伯俊ERP店仓编码/店仓名称，手工维护）
-- 语义(注意是"反向"白名单，与达人店铺表对称):
--   SP_FILL_ODS_SALES_MAIN ④小程序MERGE时，按订单当前 STORE_CODE 命中本表:
--     命中   -> STORE_CODE/STORE_NAME 保持原值不改写，
--               只更新 SALES_TYPE/VIP_MOBILE/营业员(BILL_POS_CODE/NAME) 四列
--     未命中 -> 原逻辑 6 列全改（含店铺兜底 BCHY/边城会员中心店）
--   主播规则③不受影响: ③照常改写店铺，白名单只拦④对店铺两列的覆盖；
--   白名单判断发生在③之后，用的是④执行时订单的当前 STORE_CODE
-- 幂等：DDL 用 user_tables/user_indexes 探测，GRANT 幂等，可重复执行
-- 变更: 2026-09-24 新建
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- ==========================================================
-- 1. 业务表
-- ==========================================================
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'BC_SPORTS_BI_STORE_WHITELIST';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BC_SPORTS_BI_STORE_WHITELIST (
          id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          store_code   VARCHAR2(80 CHAR) NOT NULL,
          store_name   VARCHAR2(255 CHAR) NOT NULL,
          source       VARCHAR2(20 CHAR) DEFAULT 'MANUAL' NOT NULL,
          create_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
          update_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
          create_by    VARCHAR2(50 CHAR),
          update_by    VARCHAR2(50 CHAR),
          deleted      NUMBER(1) DEFAULT 0
      )]';
    DBMS_OUTPUT.PUT_LINE('BC_SPORTS_BI_STORE_WHITELIST created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('BC_SPORTS_BI_STORE_WHITELIST already exists, skip');
  END IF;
END;
/

-- 1.1 已有环境补 source 列(2026-09-24 定时同步需求: 区分手工/自动同步行)
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
   WHERE table_name = 'BC_SPORTS_BI_STORE_WHITELIST' AND column_name = 'SOURCE';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE BC_SPORTS_BI_STORE_WHITELIST ADD (source VARCHAR2(20 CHAR) DEFAULT ''MANUAL'' NOT NULL)';
    DBMS_OUTPUT.PUT_LINE('source column added');
  ELSE
    DBMS_OUTPUT.PUT_LINE('source column already exists, skip');
  END IF;
END;
/

-- ==========================================================
-- 2. 唯一索引：未删除记录内 store_code 唯一（一个店铺只配一条，换名走编辑）
--    Oracle 无部分索引语法，用函数式唯一索引，同 uk_bi_talent_store_talent 写法
-- ==========================================================
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'UK_BI_STORE_WHITELIST_CODE';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_bi_store_whitelist_code '
                   || 'ON BC_SPORTS_BI_STORE_WHITELIST (CASE WHEN deleted = 0 THEN store_code END)';
    DBMS_OUTPUT.PUT_LINE('uk_bi_store_whitelist_code created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('uk_bi_store_whitelist_code already exists, skip');
  END IF;
END;
/

COMMENT ON TABLE  BC_SPORTS_BI_STORE_WHITELIST IS '店铺白名单（伯俊ERP店仓编码/名称；SP_FILL_ODS_SALES_MAIN④小程序更新时命中则不改写店铺两列）';
COMMENT ON COLUMN BC_SPORTS_BI_STORE_WHITELIST.store_code IS '伯俊ERP店仓编码(C_STORE.CODE)，未删除记录内唯一';
COMMENT ON COLUMN BC_SPORTS_BI_STORE_WHITELIST.store_name IS '伯俊ERP店仓名称(C_STORE.NAME)';
COMMENT ON COLUMN BC_SPORTS_BI_STORE_WHITELIST.source IS '数据来源：MANUAL 手工录入 AUTO 伯俊定时同步(C_STORE自提属性)';
COMMENT ON COLUMN BC_SPORTS_BI_STORE_WHITELIST.deleted IS '逻辑删除：0 正常 1 已删除';

-- ==========================================================
-- 3. 菜单(挂在 BI_DIR 下) + 按钮权限 + 授权给超管 role_id='1'
-- ==========================================================

-- 3.1 页面菜单 (menu_type=1)
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_STORE_WHITELIST', 'BI_DIR', '自提店铺白名单', 'bi-shield-lock', 1,
       '/bi/store-whitelist', 'bi:store-whitelist:query', 51, 1, 1,
       '维护小程序订单不改写店铺的白名单(伯俊ERP店仓,反向:命中不改写店铺两列)', NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_STORE_WHITELIST');

-- 3.2 按钮权限 (menu_type=2, 不在侧边栏显示 visible=0)
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_STORE_WHITELIST_ADD', 'BI_STORE_WHITELIST', '新增自提店铺', NULL, 2,
       NULL, 'bi:store-whitelist:add', 1, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_STORE_WHITELIST_ADD');

INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_STORE_WHITELIST_EDIT', 'BI_STORE_WHITELIST', '编辑自提店铺', NULL, 2,
       NULL, 'bi:store-whitelist:edit', 2, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_STORE_WHITELIST_EDIT');

INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_STORE_WHITELIST_DELETE', 'BI_STORE_WHITELIST', '删除自提店铺', NULL, 2,
       NULL, 'bi:store-whitelist:delete', 3, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_STORE_WHITELIST_DELETE');

-- 3.3 授权给超管角色 (role_id='1')
INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_STORE_WHITELIST', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_STORE_WHITELIST');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_STORE_WHITELIST_ADD', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_STORE_WHITELIST_ADD');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_STORE_WHITELIST_EDIT', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_STORE_WHITELIST_EDIT');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_STORE_WHITELIST_DELETE', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_STORE_WHITELIST_DELETE');

-- ==========================================================
-- 4. 数仓授权: bi_dw 的 SP_FILL_ODS_SALES_MAIN 存储过程④要读本表做白名单判断。
--    两用户同实例(192.168.5.177:orcl), 直接跨schema授权即可, 无需DB link;
--    过程是定义者权限, 必须直接授权(走角色无效)。GRANT 幂等, 重复执行不报错。
-- ==========================================================
GRANT SELECT ON BC_SPORTS.BC_SPORTS_BI_STORE_WHITELIST TO BI_DW;

-- ==========================================================
-- 5. 定时任务: 伯俊自提店铺(C_STOREATTRIB8_ID=7582, 系统配置 store.whitelist.attrib8Id 可改)
--    自动同步到本表。规则: ERP有→新增/改名(source=AUTO), ERP摘除属性→软删AUTO行,
--    手工行(source=MANUAL)永不改动。任务实现=后端 storeWhitelistSyncTask,
--    每8小时(00:00/08:00/16:00), 也可在白名单页面"从ERP同步"按钮或定时任务管理手动触发。
--    仅生产实例生效(schedule.enabled=true 由 CI 启动命令携带)。
-- ==========================================================
INSERT INTO BC_SPORTS_SYS_SCHEDULE_JOB
  (ID, JOB_NAME, TASK_KEY, CRON_EXPRESSION, STATUS, MODULE, SORT, REMARK, PARAMS, NOTIFY_STRATEGY,
   CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT RAWTOHEX(SYS_GUID()), 'ERP-同步自提店铺白名单', 'bjerp.store.whitelist.sync', '0 */8 * * *', 1,
       'BJERP', 3, '把伯俊C_STORE自提属性(默认7582,配置store.whitelist.attrib8Id)的店仓同步到自提店铺白名单;AUTO行增删改,MANUAL行不动',
       NULL, 'FAIL_ONLY', SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_SCHEDULE_JOB WHERE TASK_KEY = 'bjerp.store.whitelist.sync');

COMMIT;

EXIT;
