-- ==========================================================
-- 达人店铺管理 - 建表 + 菜单脚本 —— 主库 Oracle 执行
-- 业务表: BC_SPORTS_BI_TALENT_STORE（达人名称 + 伯俊ERP店仓编码/店仓名称，手工维护）
-- 菜单: 挂在 BI管理(BI_DIR) 下，按钮权限 新增/编辑/删除，授权给超管 role_id='1'
-- 幂等：DDL 用 user_tables/user_indexes 探测，INSERT 用 WHERE NOT EXISTS，可重复执行
-- ==========================================================
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- ==========================================================
-- 1. 业务表
-- ==========================================================
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'BC_SPORTS_BI_TALENT_STORE';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BC_SPORTS_BI_TALENT_STORE (
          id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          talent_name  VARCHAR2(100 CHAR) NOT NULL,
          store_code   VARCHAR2(80 CHAR) NOT NULL,
          store_name   VARCHAR2(255 CHAR) NOT NULL,
          create_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
          update_time  TIMESTAMP DEFAULT SYSTIMESTAMP,
          create_by    VARCHAR2(50 CHAR),
          update_by    VARCHAR2(50 CHAR),
          deleted      NUMBER(1) DEFAULT 0
      )]';
    DBMS_OUTPUT.PUT_LINE('BC_SPORTS_BI_TALENT_STORE created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('BC_SPORTS_BI_TALENT_STORE already exists, skip');
  END IF;
END;
/

-- ==========================================================
-- 2. 唯一索引：未删除记录内 talent_name 唯一（一个达人只绑定一个店仓，换绑走编辑）
--    Oracle 无部分索引语法，用函数式唯一索引，同 uk_bcp_sport_points_sporter 写法
-- ==========================================================

-- 2.1 若历史版本脚本已建过 达人+店仓组合唯一索引(UK_BI_TALENT_STORE_PAIR)，先删掉
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'UK_BI_TALENT_STORE_PAIR';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX UK_BI_TALENT_STORE_PAIR';
    DBMS_OUTPUT.PUT_LINE('uk_bi_talent_store_pair dropped (legacy pair index)');
  ELSE
    DBMS_OUTPUT.PUT_LINE('uk_bi_talent_store_pair not exists, skip drop');
  END IF;
END;
/

-- 2.2 达人名称唯一索引
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'UK_BI_TALENT_STORE_TALENT';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_bi_talent_store_talent '
                   || 'ON BC_SPORTS_BI_TALENT_STORE (CASE WHEN deleted = 0 THEN talent_name END)';
    DBMS_OUTPUT.PUT_LINE('uk_bi_talent_store_talent created');
  ELSE
    DBMS_OUTPUT.PUT_LINE('uk_bi_talent_store_talent already exists, skip');
  END IF;
END;
/

COMMENT ON TABLE  BC_SPORTS_BI_TALENT_STORE IS '达人店铺维护（达人名称+伯俊ERP店仓编码/店仓名称，手工表单维护）';
COMMENT ON COLUMN BC_SPORTS_BI_TALENT_STORE.talent_name IS '达人名称，未删除记录内唯一(一个达人只绑定一个店仓)';
COMMENT ON COLUMN BC_SPORTS_BI_TALENT_STORE.store_code IS '伯俊ERP店仓编码(C_STORE.CODE)';
COMMENT ON COLUMN BC_SPORTS_BI_TALENT_STORE.store_name IS '伯俊ERP店仓名称(C_STORE.NAME)';
COMMENT ON COLUMN BC_SPORTS_BI_TALENT_STORE.deleted IS '逻辑删除：0 正常 1 已删除';

-- ==========================================================
-- 3. 菜单(挂在 BI_DIR 下) + 按钮权限 + 授权给超管 role_id='1'
-- ==========================================================

-- 3.1 页面菜单 (menu_type=1)
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_TALENT_STORE', 'BI_DIR', '达人店铺管理', 'bi-stars', 1,
       '/bi/talent-store', 'bi:talent-store:query', 50, 1, 1,
       '维护达人名称与伯俊ERP店仓(编码/名称)的绑定关系', NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_TALENT_STORE');

-- 3.2 按钮权限 (menu_type=2, 不在侧边栏显示 visible=0)
INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_TALENT_STORE_ADD', 'BI_TALENT_STORE', '新增达人店铺', NULL, 2,
       NULL, 'bi:talent-store:add', 1, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_TALENT_STORE_ADD');

INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_TALENT_STORE_EDIT', 'BI_TALENT_STORE', '编辑达人店铺', NULL, 2,
       NULL, 'bi:talent-store:edit', 2, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_TALENT_STORE_EDIT');

INSERT INTO BC_SPORTS_SYS_MENU
  (ID, PARENT_ID, MENU_NAME, ICON, MENU_TYPE, PATH, PERMISSION, SORT, STATUS, VISIBLE,
   DESCRIPTION, ICON_COLOR, CREATE_TIME, UPDATE_TIME, CREATE_BY, UPDATE_BY, DELETED)
SELECT 'BI_TALENT_STORE_DELETE', 'BI_TALENT_STORE', '删除达人店铺', NULL, 2,
       NULL, 'bi:talent-store:delete', 3, 1, 0,
       NULL, NULL, SYSTIMESTAMP, SYSTIMESTAMP, 'admin', 'admin', 0
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_MENU WHERE ID = 'BI_TALENT_STORE_DELETE');

-- 3.3 授权给超管角色 (role_id='1')
INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_TALENT_STORE', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_TALENT_STORE');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_TALENT_STORE_ADD', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_TALENT_STORE_ADD');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_TALENT_STORE_EDIT', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_TALENT_STORE_EDIT');

INSERT INTO BC_SPORTS_SYS_ROLE_MENU (ID, ROLE_ID, MENU_ID, CREATE_TIME, CREATE_BY)
SELECT RAWTOHEX(SYS_GUID()), '1', 'BI_TALENT_STORE_DELETE', SYSTIMESTAMP, 'admin'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM BC_SPORTS_SYS_ROLE_MENU WHERE ROLE_ID = '1' AND MENU_ID = 'BI_TALENT_STORE_DELETE');

COMMIT;

EXIT;
